import {
  StateSchema,
  MessagesValue,
  type GraphNode,
  StateGraph,
  START,
  END,
} from "@langchain/langgraph";
import { z } from "zod";
import { cohereModel, gptModel, metaModel } from "./models.ai.js";
import { createAgent, HumanMessage, providerStrategy } from "langchain";

const State = new StateSchema({
  problem: z.string().default(""),
  solution_1: z.string().default(""),
  solution_2: z.string().default(""),
  judge: z
    .object({
      solution_1_score: z.number().default(0),
      solution_2_score: z.number().default(0),
      solution_1_reasoning: z.string().default(""),
      solution_2_reasoning: z.string().default(""),
    })
    .default({
      solution_1_score: 0,
      solution_2_score: 0,
      solution_1_reasoning: "",
      solution_2_reasoning: "",
    }),
});

const solutionNode: GraphNode<typeof State> = async (state) => {
  const { problem } = state;

  const [cohereResponse, metaResponse] = await Promise.all([
    cohereModel.invoke(problem),
    metaModel.invoke(problem),
  ]);

  return {
    solution_1: cohereResponse.text,
    solution_2: metaResponse.text,
  };
};

const judgeNode: GraphNode<typeof State> = async (state) => {
  const { problem, solution_1, solution_2 } = state;

  const judge = createAgent({
    model: gptModel,
    responseFormat: providerStrategy(
      z.object({
        solution_1_score: z.number().min(0).max(10),
        solution_2_score: z.number().min(0).max(10),
        solution_1_reasoning: z.string(),
        solution_2_reasoning: z.string(),
      }),
    ),
    systemPrompt: `You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores.`,
  });

  const judgeResponse = judge.invoke({
    messages: [
      new HumanMessage(`
        Problem: ${problem},
        Solution1: ${solution_1},
        Solution2: ${solution_2},
        Please evaluate the solutions and provide scores and reasoning.
        `),
    ],
  });

  const {
    solution_1_score,
    solution_2_score,
    solution_1_reasoning,
    solution_2_reasoning,
  } = (await judgeResponse).structuredResponse;

  return {
    judge: {
      solution_1_score,
      solution_2_score,
      solution_1_reasoning,
      solution_2_reasoning
    }
  }
};

const graph = new StateGraph(State)
  .addNode("solution_node", solutionNode)
  .addNode("judge_node", judgeNode)
  .addEdge(START, "solution_node")
  .addEdge("solution_node", "judge_node")
  .addEdge("judge_node", END)
  .compile();

export default async function useGraph(problem: string){
  const result = await graph.invoke({
    problem: problem
  })

  return result
}